### ISSUE TITLE
Mongo replica set

### ISSUE THREAD

**Issue by sderuiter** [aesirxio/analytics-1stparty#6]
How can I use my own Mongo replica set? I have a Mongo URI that I use to connect, which includes all members of the replica set.

**Comment by jatitoam** [comment]
Hi @sderuiter you can change the `.aesirx-1stparty.env` settings (once cloned from the dist file) to point to it.

Specifically you can change the `DBHOST` to provide your own replica URI, and the rest of the `DB` settings for port, username, password and database.

Something we lack now is the ability to disable (from configuration) the included MongoDB instance, but you can comment the lines in the `docker-compose.yaml` file: https://github.com/aesirxio/analytics-1stparty/blob/develop/docker-compose.yaml#L2-L14

**Comment by sderuiter** [comment]
Thanks, but still have trouble getting this running. 

I'm already running behind a NGINX proxy, and have my own MongoDB replicaset. 

I've tried the following .yaml file:
```
services:
  
  aesirx-analytics:
    image: aesirxio/analytics-1stparty:develop
    restart: always
    pull_policy: always
    networks:
      - backend

networks:
  backend:
    driver: bridge
```

With ENV variables defined (in my case in portainer, so *not* in a separate file):

* HTTP_POST
* DBPASS
* DBHOST.

However, this leads to:

`thread 'main' panicked at 'Configuration Error: MissingValue(
    "http_port",
)', src/config.rs:139:23`


My question: what are the minimal ENV variables I need to specify to get this running?
