### ISSUE TITLE
Replica set issues

### ISSUE THREAD

**Issue by sderuiter** [aesirxio/analytics-1stparty#8]
Hi,

As I have my own Mongo Replicaset running (and Nginx), I only want to run the Analytics.

```
services:
  
  aesirx-analytics:
    image: aesirxio/analytics-1stparty:develop
    restart: always
    pull_policy: always
    environment:
      - HTTP_PORT=8080
      - DBHOST= <My replicates URI, including ?replicaSet=rs2>
      - DBUSER=admin
      - DBNAME=aesirxanalytics
      - DBPASS= <long password> 
      - MONGO_INITDB_ROOT_PASSWORD= <long password> 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - DBPORT=27027
      - RUST_BACKTRACE=0
      - RUST_LOG="actix_web=info,actix_server=info,actix_redis=trace"
      - LICENSE=
      - RUST_CRON_TIME=15
      - ENABLE_CRONJOB=1
      - ENABLE_MIGRATION=1
      - ENABLE_API_SERVER=1
    networks:
      - backend

networks:
  backend:
    driver: bridge
```

The service finds the MongoDB server, however returns with the following error:

`thread 'main' panicked at 'Database connection error: ApiError { cause: None, message: Some("Kind: Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Set Name: rs2:27027/?retryWrites=true }, labels: {}"), error_type: InternalError }', src/main.rs:28:39`

However, I *do* have a Primary selected?
